[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_VERSION       = "0.73.0"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

	[context.split1.environment]
	HUGO_ENV     = "production"
	HUGO_VERSION = "0.73.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

	[context.deploy-preview.environment]
	HUGO_VERSION = "0.73.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

	[context.branch-deploy.environment]
	HUGO_VERSION = "0.73.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
